@extends('portal.layout')
@section('title', 'Dashboard')
@section('portal-content')
<div class="gs-hero"><div><p class="gs-eyebrow">Teacher Dashboard</p><h1>Welcome back, {{ auth('teacher')->user()->name }}.</h1><p class="gs-muted">Your current teaching and grade-sheet workflow.</p></div><div class="gs-hero-mark"><img src="{{ asset('icons/employee.png') }}" alt=""></div></div>
<div class="gs-stats">@include('portal.partials.stat', ['label'=>'Assigned Classes','value'=>$classes->count(),'hint'=>'Classes with assigned subjects','icon'=>'higher-education'])@include('portal.partials.stat', ['label'=>'Assigned Subjects','value'=>$subjectCount,'hint'=>'Subjects assigned to you','icon'=>'stack-of-books'])@include('portal.partials.stat', ['label'=>'Students Handled','value'=>$studentCount,'hint'=>'Admitted students in your classes','icon'=>'children'])@include('portal.partials.stat', ['label'=>'Grade Sheets','value'=>$sheets->count(),'hint'=>'Draft, submitted, returned, approved','icon'=>'academic-success'])</div>
<section class="gs-section"><div class="gs-section-heading"><h2>Recent Grade Sheets</h2></div><div class="gs-card"><div class="gs-table-wrap"><table class="gs-table"><thead><tr><th>Class</th><th>Subject</th><th>Quarter</th><th>Status</th><th>Updated</th></tr></thead><tbody>@forelse($sheets->take(10) as $sheet)<tr><td>{{ $sheet->class_name }}</td><td>{{ $sheet->subject_name }}</td><td>Q{{ $sheet->quarter }}</td><td><span class="gs-badge" data-status="{{ $sheet->status }}">{{ $sheet->status }}</span></td><td>{{ $sheet->updated_at?->diffForHumans() }}</td></tr>@empty<tr><td colspan="5">No grade sheets yet.</td></tr>@endforelse</tbody></table></div></div></section>
<section class="gs-section"><div class="gs-section-heading"><h2>Encoding Schedules</h2></div><div class="gs-card"><div class="gs-table-wrap"><table class="gs-table"><thead><tr><th>School Year</th><th>Quarter</th><th>Opens</th><th>Closes</th><th>Status</th></tr></thead><tbody>@forelse($schedules as $schedule)<tr><td>{{ $schedule->academicYear?->name }}</td><td>Q{{ $schedule->quarter }}</td><td>{{ $schedule->opens_at->format('M d, Y h:i A') }}</td><td>{{ $schedule->closes_at->format('M d, Y h:i A') }}</td><td><span class="gs-badge" data-status="{{ $schedule->status }}">{{ $schedule->status }}</span></td></tr>@empty<tr><td colspan="5">No schedule configured for your classes.</td></tr>@endforelse</tbody></table></div></div></section>
<div class="gs-actions"><a class="gs-btn gs-btn-primary" href="{{ route('teacher.classes') }}">View My Classes</a><a class="gs-btn" href="{{ route('teacher.history') }}">Grade History</a></div>
@endsection
