@extends('layouts.clean')
@php
    abort_unless(in_array($document, ['terms', 'privacy'], true), 404);
    $isTerms = $document === 'terms';
    $title = $isTerms ? 'Terms of Use and User Agreement' : 'Privacy Notice';
    $sections = $isTerms ? [
        ['Acceptance of Terms', 'Access to GSYS will require acceptance of the approved Terms of Use. The school must finalize the production wording before registration is enabled.'],
        ['Eligibility and Account Registration', 'Accounts are intended for eligible members of the school community. Registration information must be accurate and may require institutional verification.'],
        ['Student Accounts', 'Student registration should collect only approved personal, enrollment, and account information. A permanent unique 11-digit Student Number must be generated by the server after successful registration and remain read-only to the student.'],
        ['Parent/Guardian Accounts', 'A guardian account may access a child only after the school verifies the guardian’s identity and legitimate relationship to that student.'],
        ['Account Verification', 'The school will define the evidence, duplicate-registration checks, review steps, and outcome notices used to verify account requests.'],
        ['Account Security', 'Users should protect their credentials, use a strong password, and promptly report suspected unauthorized access.'],
        ['Authorized Use', 'GSYS is intended for legitimate educational and administrative purposes consistent with each user’s assigned access.'],
        ['Prohibited Activities', 'Users must not attempt unauthorized access, disclose another person’s records, disrupt the service, impersonate others, or misuse information obtained through GSYS.'],
        ['Academic Records and Grades', 'Grades shown in GSYS are school records. Student and guardian access is limited to approved grades that they are authorized to view.'],
        ['Accuracy and Correction of Records', 'Questions or correction requests should follow the school’s official academic-record process. Portal users should not attempt to alter records outside that process.'],
        ['Availability of the System', 'Access may be interrupted for maintenance, security, connectivity, or operational needs. The school should publish appropriate support channels.'],
        ['Intellectual Property', 'The school will identify ownership and permitted use of GSYS content, branding, and software in the approved version of these terms.'],
        ['Privacy and Personal Data', 'Personal data is handled under the separate Privacy Notice and applicable school policies and law.'],
        ['Security Responsibilities', 'The school and users share responsibilities for secure access, appropriate devices, accurate contact information, and timely incident reporting.'],
        ['Suspension/Termination of Accounts', 'The school may restrict an account when needed to investigate security, eligibility, or policy concerns, subject to applicable procedures and rights.'],
        ['Changes to the Terms', 'Material updates should be dated, communicated clearly, and presented for renewed agreement when required.'],
        ['Governing Law', 'The final terms should identify applicable Philippine law and school policies after legal review.'],
        ['Contact Information', 'Insert the school’s approved office, postal address, email address, telephone number, and support hours before publication.'],
        ['Effective Date / Version', 'Draft UI copy — version and effective date to be assigned after school and legal/privacy approval.'],
    ] : [
        ['Who Operates GSYS', 'GSYS is intended to be operated by Cauayan City National High School. Confirm the responsible school office and official contact details before publication.'],
        ['Personal Data Collected', 'The service may process identifying, contact, account, relationship, enrollment, class, and academic-record information needed for authorized school purposes.'],
        ['Student Information Processed', 'This may include the server-generated Student Number, name, date of birth, sex, address, enrollment information, subjects, and approved quarterly grades. Collect only what the approved workflow requires.'],
        ['Guardian Information Processed', 'This may include name, email address, contact number, declared relationship, verification evidence, and authorized child links.'],
        ['Account Information', 'Usernames, password hashes, verification status, session and security information, and relevant account audit records may be processed. Passwords must never be stored in readable form.'],
        ['Purpose of Processing', 'Information is used to provide secure portal access, verify eligibility, manage authorized relationships, display approved records, support corrections, and protect the system.'],
        ['Lawful Basis for Processing', 'The school’s privacy representative must document the applicable lawful bases under Philippine data-protection requirements and relevant education mandates.'],
        ['Who May Access the Information', 'Access should be limited by role and purpose: the student, authorized guardians, assigned teachers, and staff with institutional permission.'],
        ['Grade Visibility', 'Students may view only their own approved grades. Draft, submitted, returned, and unapproved grades must not be published to student or guardian accounts.'],
        ['Guardian-Child Access', 'Guardians may view approved grades only for children whose relationship and authorization have been verified. Knowing a student number is not sufficient.'],
        ['Data Retention', 'The school must define retention periods for registration requests, account data, verification evidence, access records, and academic information, including secure disposal rules.'],
        ['Security Measures', 'Controls should include authenticated access, least-privilege authorization, secure password handling, encrypted transport, audit logs, monitoring, backups, and incident response.'],
        ['Data-Subject Rights', 'Individuals may have rights to information, access, correction, objection, restriction, erasure where applicable, and complaint under relevant law. Requests remain subject to lawful school-record obligations.'],
        ['Requests for Correction/Access', 'Insert the approved process, identity-verification steps, expected response period, and responsible school office for access or correction requests.'],
        ['School/Privacy Contact', 'Insert the name or office of the school privacy representative, official email, telephone number, and postal address before publication.'],
        ['Complaint/Contact Information', 'Explain how concerns may be raised with the school and, where applicable, with the National Privacy Commission. Confirm the wording and current contact channel before publication.'],
        ['Updates to this Privacy Notice', 'Material changes should be dated and communicated in clear language through appropriate school channels.'],
        ['Effective Date / Version', 'Draft UI copy — version and effective date to be assigned after school and privacy review.'],
    ];
@endphp
@section('title', $title)
@section('clean')
@include('portal.partials.public-styles')
<main class="gs-public"><article class="gs-public-shell gs-document">
    <header class="gs-public-head"><div><p>Cauayan City National High School / GSYS</p><h1>{{ $title }}</h1></div><a href="javascript:history.back()">Back</a></header>
    <div class="gs-public-body">
        <p class="gs-version"><strong>Draft for review:</strong> This page provides structured, plain-language placeholder content. It is not final legal advice or an approved school policy. School leadership and appropriate legal/privacy personnel must review it before registration is enabled.</p>
        @foreach($sections as $index => [$heading, $copy])<section id="section-{{ $index + 1 }}"><h2>{{ $index + 1 }}. {{ $heading }}</h2><p>{{ $copy }}</p></section>@endforeach
        <div class="gs-actions"><a class="gs-btn" href="{{ route('legal.terms') }}">Terms of Use</a><a class="gs-btn" href="{{ route('legal.privacy') }}">Privacy Notice</a><a class="gs-btn gs-btn-primary" href="{{ route('signin') }}">Return to Sign In</a></div>
    </div>
</article></main>
@endsection
