@extends('layouts.app')
@section('title', 'Account Registrations')
@section('content')
@include('portal.partials.styles')
<div class="gs-portal" style="padding:24px" data-account-registrations>
    <div class="gs-page-header"><div><p class="gs-eyebrow">Accounts</p><h1>Account Registrations</h1><p>Review Student and Guardian account requests before portal activation.</p></div></div>
    <p class="gs-alert gs-alert-warning"><strong>Frontend preview:</strong> Records below are samples. Activate, Reject, and Deactivate change only this page and do not affect sign-in access.</p>
    <div class="gs-card gs-section"><div class="gs-toolbar" role="tablist" aria-label="Registration status"><button type="button" class="gs-btn gs-btn-primary" role="tab" aria-selected="true" data-registration-tab="PENDING">Pending</button><button type="button" class="gs-btn" role="tab" aria-selected="false" data-registration-tab="ACTIVE">Active</button><button type="button" class="gs-btn" role="tab" aria-selected="false" data-registration-tab="REJECTED">Rejected</button><button type="button" class="gs-btn" role="tab" aria-selected="false" data-registration-tab="DEACTIVATED">Deactivated</button></div></div>
    <section data-registration-list>
        <form class="gs-card gs-section" data-registration-filters><div class="gs-toolbar"><label class="gs-field">Account Type<select name="type"><option value="">All types</option><option>Student</option><option>Guardian</option></select></label><label class="gs-field">Date Registered<select name="date"><option value="">Any date</option><option value="today">Today</option><option value="week">Last 7 days</option><option value="month">Last 30 days</option></select></label><label class="gs-field">Status<select name="status"><option value="">Current tab</option><option>PENDING</option><option>ACTIVE</option><option>REJECTED</option><option>DEACTIVATED</option></select></label><button class="gs-btn gs-btn-primary">Apply</button><button class="gs-btn" type="reset">Reset</button><label class="gs-field gs-search">Search<input type="search" name="search" placeholder="Name, student number, or email"></label></div></form>
        <div class="gs-card"><div class="gs-table-wrap" tabindex="0" role="region" aria-label="Account registration requests"><table class="gs-table"><thead><tr><th>Name</th><th>Account Type</th><th>Student No.</th><th>Registered</th><th>Status</th><th>Action</th></tr></thead><tbody data-registration-rows></tbody></table></div></div>
    </section>
    <section data-registration-review hidden tabindex="-1"><div class="gs-section-heading"><h2>Registration Details</h2><button type="button" class="gs-btn" data-back-registrations>Back to Registrations</button></div><div class="gs-card gs-section"><div class="gs-card-body"><dl class="gs-context" data-registration-details></dl><div class="gs-alert gs-alert-warning" data-guardian-claim hidden><strong>Claimed Child</strong><p data-guardian-claim-copy></p><p>Confirm the guardian-child relationship through an approved school process before activation.</p></div></div><div class="gs-savebar"><button type="button" class="gs-btn gs-btn-danger" data-reject-open>Reject Registration</button><button type="button" class="gs-btn gs-btn-danger" data-deactivate-open hidden>Deactivate Account</button><button type="button" class="gs-btn gs-btn-primary" data-activate-open>Activate Account</button></div></div><p class="gs-alert" data-registration-feedback role="status">Reviewing sample data. No account status has changed.</p></section>
    <dialog class="gs-dialog" data-activate-dialog aria-labelledby="activate-title"><div class="gs-dialog-head"><h2 id="activate-title">Activate Account?</h2><button type="button" class="gs-close" data-registration-cancel aria-label="Close">&times;</button></div><div class="gs-card-body"><p data-activate-summary></p><p class="gs-alert gs-alert-warning" data-activation-warning></p><p class="gs-footnote">Frontend preview only. This does not allow the user to sign in.</p><div class="gs-actions" style="justify-content:flex-end"><button type="button" class="gs-btn" data-registration-cancel>Cancel</button><button type="button" class="gs-btn gs-btn-primary" data-activate-confirm>Activate Account</button></div></div></dialog>
    <dialog class="gs-dialog" data-reject-dialog aria-labelledby="reject-title"><div class="gs-dialog-head"><h2 id="reject-title">Reject Registration</h2><button type="button" class="gs-close" data-registration-cancel aria-label="Close">&times;</button></div><form class="gs-card-body" data-reject-form><label class="gs-field">Reason <textarea name="reason" rows="4" maxlength="1000" required placeholder="Explain why this registration cannot be approved"></textarea></label><p class="gs-muted gs-small">Examples include unable to verify enrollment, possible duplicate registration, or an unverified guardian relationship. Enter the actual reason.</p><div class="gs-actions" style="justify-content:flex-end"><button type="button" class="gs-btn" data-registration-cancel>Cancel</button><button class="gs-btn gs-btn-danger">Reject</button></div></form></dialog>
    <dialog class="gs-dialog" data-deactivate-dialog aria-labelledby="deactivate-title"><div class="gs-dialog-head"><h2 id="deactivate-title">Deactivate Account?</h2><button type="button" class="gs-close" data-registration-cancel aria-label="Close">&times;</button></div><div class="gs-card-body"><p data-deactivate-summary></p><p class="gs-alert gs-alert-warning">A deactivated account cannot sign in. Deactivation must not delete the underlying academic or person record.</p><p class="gs-footnote">Frontend preview only.</p><div class="gs-actions" style="justify-content:flex-end"><button type="button" class="gs-btn" data-registration-cancel>Cancel</button><button type="button" class="gs-btn gs-btn-danger" data-deactivate-confirm>Deactivate Account</button></div></div></dialog>
</div>
<script src="{{ asset('js/account-registrations.js') }}" defer></script>
@endsection
