@extends('layouts.app')
@section('title', 'Registration Review')
@section('content')
@include('portal.partials.styles')
<div class="gs-portal" style="padding:24px">
    <div class="gs-page-header"><div><p class="gs-eyebrow">Accounts</p><h1>Registration Review</h1><p>{{ ucfirst($type) }} account #{{ $account->id }}</p></div><a class="gs-btn" href="{{ route('configuration.accounts.registrations', ['type'=>$type, 'status'=>$account->status]) }}">Back</a></div>
    @if(session('success'))<p class="gs-alert">{{ session('success') }}</p>@endif
    @if($errors->any())<p class="gs-error">{{ $errors->first() }}</p>@endif
    <div class="gs-card gs-section"><div class="gs-card-body"><dl class="gs-context"><div><dt>Name</dt><dd>{{ $type === 'student' ? ($account->info?->name ?? $account->username) : ($account->name ?: $account->username) }}</dd></div><div><dt>Username</dt><dd>{{ $account->username }}</dd></div><div><dt>Email</dt><dd>{{ $account->email }}</dd></div><div><dt>Status</dt><dd><span class="gs-badge" data-status="{{ $account->status }}">{{ $account->status }}</span></dd></div>@if($type==='student')<div><dt>Student Number</dt><dd>{{ $account->student_number }}</dd></div><div><dt>Birthdate</dt><dd>{{ $account->info?->birthdate }}</dd></div>@endif</dl></div></div>
    @if($type === 'guardian')
        <section class="gs-section"><div class="gs-section-heading"><h2>Child Claims</h2></div><div class="gs-card"><div class="gs-table-wrap"><table class="gs-table"><thead><tr><th>Student</th><th>Number</th><th>Relationship</th><th>Status</th><th>Review</th></tr></thead><tbody>@forelse($links as $link)<tr><td>{{ $link->student?->info?->name ?? $link->claimed_student_name }}</td><td>{{ $link->student?->student_number }}</td><td>{{ $link->relationship }}</td><td><span class="gs-badge" data-status="{{ $link->status }}">{{ $link->status }}</span></td><td><form method="POST" action="{{ route('configuration.accounts.guardians.childs.verify', $link) }}" class="gs-actions">@csrf<select name="status"><option value="VERIFIED">VERIFIED</option><option value="REJECTED">REJECTED</option></select><input name="verification_note" placeholder="Verification note" required><button class="gs-btn">Save</button></form></td></tr>@empty<tr><td colspan="5">No child claims.</td></tr>@endforelse</tbody></table></div></div></section>
    @endif
    <section class="gs-section"><div class="gs-section-heading"><h2>Account Action</h2></div><div class="gs-card gs-card-body"><form method="POST" action="{{ route('configuration.accounts.registrations.update', [$type, $account->id]) }}" class="gs-grid">@csrf<label class="gs-field">Action<select name="action" required><option value="activate">Activate</option><option value="reject">Reject</option><option value="deactivate">Deactivate</option></select></label><label class="gs-field gs-field-wide">Reason<textarea name="reason" rows="3" placeholder="Required when rejecting"></textarea></label><div class="gs-actions"><button class="gs-btn gs-btn-primary">Save Account Status</button></div></form></div></section>
    <section class="gs-section"><div class="gs-section-heading"><h2>Audit Trail</h2></div><div class="gs-card"><div class="gs-table-wrap"><table class="gs-table"><thead><tr><th>When</th><th>Actor</th><th>Action</th></tr></thead><tbody>@forelse($audit as $event)<tr><td>{{ $event->created_at }}</td><td>{{ $event->actor_type }} #{{ $event->actor_id }}</td><td>{{ $event->action }}</td></tr>@empty<tr><td colspan="3">No audit events yet.</td></tr>@endforelse</tbody></table></div></div></section>
</div>
@endsection
