@extends('layouts.app')
@section('title', 'Registration Review')
@section('content')
@include('portal.partials.styles')
<div class="gs-portal" style="padding:24px">
    <div class="gs-page-header"><div><p class="gs-eyebrow">Accounts</p><h1>Registration Review</h1><p>{{ ucfirst($type) }} account #{{ $account->id }}</p></div><a class="gs-btn" href="{{ route('configuration.accounts.registrations', ['type'=>$type, 'status'=>$account->status]) }}">Back</a></div>
    @if(session('success'))<p class="gs-alert">{{ session('success') }}</p>@endif
    @if($errors->any())<p class="gs-error">{{ $errors->first() }}</p>@endif
    <div class="gs-card gs-section"><div class="gs-card-body"><dl class="gs-context"><div><dt>Name</dt><dd>{{ $account->name ?: $account->username }}</dd></div><div><dt>Username</dt><dd>{{ $account->username }}</dd></div><div><dt>Email</dt><dd>{{ $account->email }}</dd></div><div><dt>Status</dt><dd><span class="gs-badge" data-status="{{ $account->status }}">{{ $account->status }}</span></dd></div>@if($type==='student')<div><dt>Official Student Number</dt><dd>{{ $account->student?->student_number ?? 'Not linked' }}</dd></div><div><dt>Birthdate</dt><dd>{{ $account->birthdate?->format('Y-m-d') }}</dd></div><div><dt>Contact</dt><dd>{{ $account->contact }}</dd></div><div><dt>Address</dt><dd>{{ $account->address }}</dd></div><div><dt>Academic Record</dt><dd>{{ $account->student?->info?->name ?? 'Not linked' }}</dd></div>@endif</dl></div></div>
    @if($type === 'student')
        <section class="gs-section"><div class="gs-section-heading"><h2>Academic Student Record</h2></div>
            @if($account->student_id)
                <div class="gs-card gs-card-body"><strong>{{ $account->student?->info?->name }}</strong> — {{ $account->student?->student_number }}<br>{{ $account->student?->info?->gradeLevel?->name }} / {{ $account->student?->info?->schoolClass?->name }} / {{ $account->student?->info?->academicYear?->name }}</div>
            @else
                <form method="GET" action="{{ route('configuration.accounts.registrations.show', ['type'=>'student','id'=>$account->id]) }}" class="gs-card gs-card-body gs-actions"><input name="record_search" value="{{ request('record_search') }}" placeholder="Student number, name, grade, section, or school year" required class="gs-field"><button class="gs-btn gs-btn-primary">Search Student Record</button></form>
                @if(request()->filled('record_search'))
                    <div class="gs-card"><div class="gs-table-wrap"><table class="gs-table"><thead><tr><th>Student</th><th>Student Number</th><th>Grade</th><th>Section</th><th>School Year</th><th>Portal Account</th><th></th></tr></thead><tbody>@forelse($records as $record)<tr><td>{{ $record->info?->name }}</td><td>{{ $record->student_number }}</td><td>{{ $record->info?->gradeLevel?->name }}</td><td>{{ $record->info?->schoolClass?->name }}</td><td>{{ $record->info?->academicYear?->name }}</td><td>{{ $record->portalAccount?->status ?? 'NOT LINKED' }}</td><td>@unless($record->portalAccount)<a class="gs-btn" href="{{ route('configuration.accounts.registrations.show', ['type'=>'student','id'=>$account->id,'record_id'=>$record->id,'record_search'=>request('record_search')]) }}">Select</a>@endunless</td></tr>@empty<tr><td colspan="7">No matching academic record. Create or complete it in Admin Student Management, then search again.</td></tr>@endforelse</tbody></table></div></div>
                @endif
                @if($selectedStudent)
                    <div class="gs-card gs-card-body"><h3>Link Student Account</h3><p>Registered account: <strong>{{ $account->name }}</strong></p><p>Academic record: <strong>{{ $selectedStudent->info?->name }}</strong> — {{ $selectedStudent->student_number }} / {{ $selectedStudent->info?->gradeLevel?->name }} / {{ $selectedStudent->info?->schoolClass?->name }} / {{ $selectedStudent->info?->academicYear?->name }}</p>
                        @if($selectedStudent->portalAccount)<p>This academic student already has a portal account.</p>@else<form method="POST" action="{{ route('configuration.accounts.registrations.students.link',$account) }}">@csrf<input type="hidden" name="student_id" value="{{ $selectedStudent->id }}"><label><input type="checkbox" name="confirm" value="1" required> I verified this academic record belongs to the registered student.</label><div class="gs-actions"><a class="gs-btn" href="{{ route('configuration.accounts.registrations.show',['type'=>'student','id'=>$account->id]) }}">Cancel</a><button class="gs-btn gs-btn-primary">Link &amp; Activate</button></div></form>@endif
                    </div>
                @endif
                <p class="gs-muted">No record found? Use <a href="{{ route('configuration.accounts.students') }}">Admin Student Management</a> to create or complete the academic record and enrollment first.</p>
            @endif
        </section>
    @endif
    @if($type === 'guardian')
        <section class="gs-section"><div class="gs-section-heading"><h2>Children</h2><a class="gs-btn" href="{{ route('configuration.accounts.guardians', ['search'=>$account->username]) }}">Manage Children</a></div><div class="gs-card"><div class="gs-table-wrap"><table class="gs-table"><thead><tr><th>Student</th><th>Student No.</th><th>Relationship</th></tr></thead><tbody>@forelse($links as $link)<tr><td>{{ $link->student?->info?->name ?? $link->student?->username }}</td><td>{{ $link->student?->student_number }}</td><td>{{ $link->relationship ?? '-' }}</td></tr>@empty<tr><td colspan="3">No children linked.</td></tr>@endforelse</tbody></table></div></div></section>
    @endif
    <section class="gs-section"><div class="gs-section-heading"><h2>Account Action</h2></div><div class="gs-card gs-card-body"><form method="POST" action="{{ route('configuration.accounts.registrations.update', [$type, $account->id]) }}" class="gs-grid">@csrf<label class="gs-field">Action<select name="action" required>@if($type === 'guardian' || $account->student_id)<option value="activate">Activate</option>@endif<option value="reject">Reject</option><option value="deactivate">Deactivate</option></select></label><label class="gs-field gs-field-wide">Reason<textarea name="reason" rows="3" placeholder="Required when rejecting"></textarea></label><div class="gs-actions"><button class="gs-btn gs-btn-primary">Save Account Status</button></div></form></div></section>
    <section class="gs-section"><div class="gs-section-heading"><h2>Audit Trail</h2></div><div class="gs-card"><div class="gs-table-wrap"><table class="gs-table"><thead><tr><th>When</th><th>Actor</th><th>Action</th></tr></thead><tbody>@forelse($audit as $event)<tr><td>{{ $event->created_at }}</td><td>{{ $event->actor_type }} #{{ $event->actor_id }}</td><td>{{ $event->action }}</td></tr>@empty<tr><td colspan="3">No audit events yet.</td></tr>@endforelse</tbody></table></div></div></section>
</div>
@endsection
