@extends('layouts.clean')
@php
    abort_unless(in_array($portal, ['student', 'guardian'], true), 404);
    $isStudent = $portal === 'student';
    $steps = $isStudent ? ['Personal Information', 'Academic Information', 'Account Information', 'Terms & Privacy', 'Review'] : ['Guardian Information', 'Link Child', 'Account Credentials', 'Terms & Privacy'];
@endphp
@section('title', ucfirst($portal).' Registration')
@section('clean')
@include('portal.partials.public-styles')
<main class="gs-public" data-registration data-portal="{{ $portal }}">
    <div class="gs-public-shell">
        <header class="gs-public-head"><div><p>Cauayan City National High School</p><h1>{{ ucfirst($portal) }} Registration</h1></div><a href="{{ route('portal.login', ['portal' => $portal]) }}">Sign In</a></header>
        <div class="gs-public-body">
            <p class="gs-notice gs-warning"><strong>Frontend preview:</strong> This form does not verify records, create an account, send a code, or submit data.</p>
            <div class="gs-stepper" style="--steps:{{ count($steps) }}" aria-label="Registration progress">@foreach($steps as $index => $label)<div class="gs-step" data-step-indicator="{{ $index + 1 }}" @if($index === 0) aria-current="step" @endif>Step {{ $index + 1 }}<br>{{ $label }}</div>@endforeach</div>
            <form data-registration-form novalidate>
                @if($isStudent)
                    <section class="gs-panel" data-step="1"><h2>Personal Information</h2><p class="gs-muted">Enter your personal details as they should appear in your school record.</p><div class="gs-notice"><strong>Student Number:</strong> The system will generate a unique 11-digit identifier after successful future registration. You will never enter or edit it here.</div><div class="gs-grid"><label class="gs-field">First Name <span class="gs-required">Required</span><input name="first_name" autocomplete="given-name" required></label><label class="gs-field">Middle Name<input name="middle_name" autocomplete="additional-name"></label><label class="gs-field">Last Name <span class="gs-required">Required</span><input name="last_name" autocomplete="family-name" required></label><label class="gs-field">Suffix<input name="suffix" autocomplete="honorific-suffix" placeholder="Optional"></label><label class="gs-field">Date of Birth <span class="gs-required">Required</span><input type="date" name="birthdate" required></label><label class="gs-field">Sex <span class="gs-required">Required</span><select name="sex" required><option value="">Select</option><option>Female</option><option>Male</option></select></label><label class="gs-field gs-field-wide">Address<textarea name="address" rows="3" autocomplete="street-address"></textarea></label></div></section>
                    <section class="gs-panel" data-step="2" hidden><h2>Academic / Enrollment Information</h2><p class="gs-muted">Provide the school information required for enrollment review. Classes and sections are assigned through the approved school process and cannot be selected here.</p><div class="gs-grid"><label class="gs-field">Grade Level <span class="gs-required">Required</span><input name="grade_level" required placeholder="Enter current grade level"><small>The production form should load approved grade levels from GSYS.</small></label><label class="gs-field">School Year <span class="gs-required">Required</span><input name="school_year" required placeholder="Example: 2026-2027" pattern="\d{4}-\d{4}"><small>The production form should load configured school years from GSYS.</small></label></div><div class="gs-notice gs-warning">Submitting enrollment information must not automatically assign a class, section, or academic status. Those decisions remain subject to school verification.</div></section>
                    <section class="gs-panel" data-step="3" hidden><h2>Account Information</h2><p class="gs-muted">Create the credentials you will use after the future registration process is approved.</p><div class="gs-grid"><label class="gs-field">Email <span class="gs-required">Required</span><input type="email" name="email" autocomplete="email" required></label><label class="gs-field">Username <span class="gs-required">Required</span><input name="username" autocomplete="username" required></label>@include('portal.partials.registration-passwords')</div></section>
                    <section class="gs-panel" data-step="4" hidden><h2>Terms and Privacy</h2><p class="gs-muted">Review both documents before requesting registration.</p><div class="gs-doc-links"><a href="{{ route('legal.terms') }}" target="_blank" rel="noopener">Read Terms of Use</a><a href="{{ route('legal.privacy') }}" target="_blank" rel="noopener">Read Privacy Notice</a></div><label class="gs-check"><input type="checkbox" name="terms" required><span>I have read and agree to the Terms of Use and User Agreement.</span></label><label class="gs-check"><input type="checkbox" name="privacy" required><span>I acknowledge that I have read the Privacy Notice.</span></label></section>
                    <section class="gs-panel" data-step="5" data-review hidden><h2>Review Your Information</h2><p class="gs-muted">Confirm your information before previewing registration.</p><h3>Personal Information</h3><dl class="gs-summary"><div><dt>Name</dt><dd data-review-value="name">—</dd></div><div><dt>Date of Birth</dt><dd data-review-value="birthdate">—</dd></div><div><dt>Sex</dt><dd data-review-value="sex">—</dd></div><div><dt>Address</dt><dd data-review-value="address">Not provided</dd></div></dl><h3>Academic Information</h3><dl class="gs-summary"><div><dt>Grade Level</dt><dd data-review-value="grade_level">—</dd></div><div><dt>School Year</dt><dd data-review-value="school_year">—</dd></div></dl><h3>Account</h3><dl class="gs-summary"><div><dt>Email</dt><dd data-review-value="email">—</dd></div><div><dt>Username</dt><dd data-review-value="username">—</dd></div><div><dt>Student Number</dt><dd>Will be generated after registration</dd></div></dl></section>
                @else
                    <section class="gs-panel" data-step="1"><h2>Guardian Information</h2><p class="gs-muted">Provide the contact details that will eventually be checked by the school.</p><div class="gs-grid"><label class="gs-field">First Name <span class="gs-required">Required</span><input name="first_name" autocomplete="given-name" required></label><label class="gs-field">Middle Name<input name="middle_name" autocomplete="additional-name"></label><label class="gs-field">Last Name <span class="gs-required">Required</span><input name="last_name" autocomplete="family-name" required></label><label class="gs-field">Email <span class="gs-required">Required</span><input type="email" name="guardian_email" autocomplete="email" required></label><label class="gs-field gs-field-wide">Contact Number <span class="gs-required">Required</span><input type="tel" name="contact" autocomplete="tel" required></label></div></section>
                    <section class="gs-panel" data-step="2" hidden><h2>Link Your Child</h2><p class="gs-muted">Enter an existing student record and the relationship that the school should verify.</p><div class="gs-notice gs-warning">A student number alone is never sufficient authorization to access grades. Guardian identity and relationship must be verified by the future backend.</div><div class="gs-grid"><label class="gs-field">Student Number <span class="gs-required">Required</span><input name="student_number" required></label><label class="gs-field">Student Name <span class="gs-required">Required</span><input name="student_name" required></label><label class="gs-field gs-field-wide">Relationship <span class="gs-required">Required</span><select name="relationship" required><option value="">Select relationship</option><option>Parent</option><option>Legal Guardian</option><option>Other authorized guardian</option></select></label></div><div class="gs-link-child"><strong>Verification pending</strong><p class="gs-muted">No student information or grades are retrieved in this preview.</p></div></section>
                    <section class="gs-panel" data-step="3" hidden><h2>Account Credentials</h2><p class="gs-muted">Create credentials after guardian and child-link verification is completed in the future workflow.</p><div class="gs-grid"><label class="gs-field">Username <span class="gs-required">Required</span><input name="username" autocomplete="username" required></label><label class="gs-field">Email <span class="gs-required">Required</span><input type="email" name="email" autocomplete="email" required></label>@include('portal.partials.registration-passwords')</div></section>
                @endif
                @unless($isStudent)<section class="gs-panel" data-step="{{ count($steps) }}" hidden><h2>Terms and Privacy</h2><p class="gs-muted">Review both documents before requesting an account.</p><div class="gs-doc-links"><a href="{{ route('legal.terms') }}" target="_blank" rel="noopener">View Terms of Use</a><a href="{{ route('legal.privacy') }}" target="_blank" rel="noopener">View Privacy Notice</a></div><label class="gs-check"><input type="checkbox" name="terms" required><span>I have read and agree to the Terms of Use and User Agreement.</span></label><label class="gs-check"><input type="checkbox" name="privacy" required><span>I acknowledge that I have read the Privacy Notice.</span></label></section>@endunless
                <section class="gs-panel gs-success" data-success tabindex="-1" hidden><span class="gs-success-mark" aria-hidden="true">✓</span><h2>{{ $isStudent ? 'Registration Successful (Preview)' : 'Account Registration Received (Preview)' }}</h2><span class="gs-pending-badge">Pending Activation</span>@if($isStudent)<p class="gs-muted">In the completed workflow, your registration will be submitted for staff review. No account or Student Number was created by this preview.</p><div class="gs-student-number"><span>Your Student Number</span><strong data-generated-student-number>Generated securely by the server</strong><small>Keep the assigned 11-digit number for your school records.</small></div><p class="gs-notice gs-warning">An authorized school staff member must review and activate the account before Student Portal access is allowed.</p><button class="gs-btn" type="button" disabled title="Available after the backend supplies a Student Number">Copy Student Number</button><a class="gs-btn gs-btn-primary" href="{{ route('portal.login', ['portal' => $portal]) }}">Return to Sign In</a>@else<p class="gs-muted">In the completed workflow, the registration and claimed relationship will be submitted for staff review. This preview collected no data and created no account.</p><p class="gs-notice gs-warning">The account remains pending until authorized staff verifies the guardian-child relationship and activates it. Pending Guardians cannot access student grades.</p><a class="gs-btn gs-btn-primary" href="{{ route('portal.login', ['portal' => $portal]) }}">Return to Sign In</a>@endif</section>
                <p class="gs-error" data-form-error role="alert"></p>
                <div class="gs-actions" data-step-actions><button class="gs-btn" type="button" data-back hidden>Back</button><button class="gs-btn gs-btn-primary" type="button" data-next>Continue</button></div>
            </form>
            <details class="gs-status-preview"><summary>Preview future registration states</summary><div class="gs-status-grid"><span>Invalid student information</span><span>Account already registered</span><span>Relationship not verified</span><span>Weak password</span><span>Password mismatch</span><span>Expired verification</span><span>Registration unavailable</span><span>Pending verification</span></div></details>
            <p class="gs-existing">Already have an account? <a href="{{ route('portal.login', ['portal' => $portal]) }}">Sign In</a></p>
        </div>
    </div>
</main>
<script src="{{ asset('js/portal-registration.js') }}" defer></script>
@endsection
